name: FTP Deploy
permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Synchronize files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /domains/degran.de/public_html/niels/
          dry-run: false
          exclude: |
            .editorconfig
            .gitignore
            .git/**
            .github/**
            assets/niels-degrande-cv.pdf
            README.md
